apiVersion: v1
kind: Service
metadata:
  name: {{ include "radix.fullname" . }}-api
  labels:
    {{- include "radix.labels" . | nindent 4 }}
spec:
  type: {{ .Values.radixapi.service.type }}
  ports:
    - port: {{ .Values.radixapi.service.port }}
      targetPort: {{ .Values.radixapi.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "radix.selectorLabels" . | nindent 4 }}
