---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radix-volume-claim
  namespace: radix
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: {{ .Values.efs.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.efs.storageSize}}